# Change these first
owner: DotGov-Dev # Your GitHub organization or username, where this repository lives
repo: govUpTime # The name of this repository

sites:
  # Top domains from https://analytics.usa.gov/
  
  # USPS
  - name: tools.usps.com
    url: https://tools.usps.com
  - name: reg.usps.com
    url: https://reg.usps.com
  - name: www.usps.com
    url: https://www.usps.com
  - name: informeddelivery.usps.com
    url: https://informeddelivery.usps.com

  # NIH
  - name: www.ncbi.nlm.nih.gov
    url: https://www.ncbi.nlm.nih.gov  
  - name: pubmed.ncbi.nlm.nih.gov
    url: https://pubmed.ncbi.nlm.nih.gov
  - name: medlineplus.gov
    url: https://medlineplus.gov

  # Weather.gov
  - name: forecast.weather.gov
    url: https://forecast.weather.gov

 # IRS
  - name: www.irs.gov
    url: https://www.irs.gov

  # Login.gov
  - name: secure.login.gov
    url: https://secure.login.gov

  - name: www.cdc.gov
    url: www.cdc.gov

  - name: www.ssa.gov
    url: www.ssa.gov

  - name: studentaid.gov
    url: studentaid.gov
    
  - name: www.weather.gov
    url: www.weather.gov
    
  - name: www.nps.gov
    url: www.nps.gov

  - name: www.uscis.gov
    url: www.uscis.gov

  - name: travel.state.gov
    url: travel.state.gov

  - name: www.va.gov
    url: www.va.gov
  
  - name: www.usajobs.gov
    url: www.usajobs.gov
    
  - name: radar.weather.gov
    url: radar.weather.gov
    
  - name: ceac.state.gov
    url: ceac.state.gov

  - name: ais.usvisa-info.com
    url: ais.usvisa-info.com

  - name: www.fda.gov
    url: www.fda.gov

  - name: egov.uscis.gov
    url: egov.uscis.gov

  - name: www.myhealth.va.gov
    url: www.myhealth.va.gov

  - name: www.medicare.gov
    url: www.medicare.gov
  
  - name: www.justice.gov
    url: www.justice.gov

  - name: www.nhlbi.nih.gov
    url: www.nhlbi.nih.gov

  - name: www.cancer.gov
    url: www.cancer.gov
    
  - name: www.usa.gov
    url: www.usa.gov




  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /govUpTime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: govUpTime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
